server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
    ip-address: true
  client:
    register-with-eureka: false # Prevents the server from registering with itself
    fetch-registry: false      # Prevents the server from fetching the registry
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
