server:
  port: 8001

keycloak:
  auth-server-url: http://localhost:8080
  realm: amazon
  admin-username: admin
  admin-password: admin
  client-id: user-service-client

spring:
  data:
    mongodb:
      username: admin
      password: admin
      additional-hosts: localhost
      port: 27017
      database: user
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true