server:
  port: 8001

keycloak:
  server-url: http://localhost:8080
  realm: amazon
  client-id: user-service-client
  client-secret: SSLNN7GHNqZrPsidIualpVZ2XB635o09

spring:
  data:
    mongodb:
      username: admin
      password: admin
      additional-hosts: localhost
      port: 27017
      database: user
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid_connect/certs

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true